### ISSUE TITLE
how to set dynamixel parameters for velocity and acceleration in ROS2

### ISSUE THREAD

**Issue by patrickwasp** [ROBOTIS-GIT/DynamixelSDK#596]
1. Which DYNAMIXEL SDK version do you use?
  - `3.7.60`

2. Which programming language/tool do you use?
  - `ROS2`

3. Which operating system do you use?
  - `ubuntu 22.04`

3. Which USB serial converter do you use?
  - `U2D2`

4. Which DYNAMIXEL do you use?
  - `XM430-W350`

5. Have you searched the issue from the closed issue threads?
 - `yes`

7. Please describe the issue in detail
 - when I set the position the motor moves too fast. How do I set the acceleration and velocity profile? 

9. How can we reproduce the issue?
- create a launch file:

```yaml
launch: 

- node:
    pkg: "dynamixel_sdk_examples"
    exec: "read_write_node"
    name: "read_write_node"
```

- run: `rostopic pub -1 /set_position dynamixel_sdk_examples/SetPosition "{id: 2, position: 1000}"`
- observe the motor moving too fast
